# .streamlit/secrets.toml

[connections.postgresql]
dialect = "postgresql"
host = "openrte.com"
port = "60090"
database = "mqtt_klaeng_sub_iotsensor"
username = "openrte"
password = "dhAPIQtwNWf0EXr3"